### ISSUE TITLE
Crash when placing items in weaver

### ISSUE THREAD

**Issue by MegaLP** [P03W/Veneficium#2]
[08:49:03] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_2960 net.minecraft.class_3414.method_14833()'
        at net.vene.common.block.SCCSBlock.method_9534(SCCSBlock.java:88) ~[Veneficium-1.2.0.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:894) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:328) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by SilverAndro** [comment]
In the future, bug report titles should be concise, you should provide if your running on a dedicated server, your minecraft version, and any additional mods

This is luckily a quite simple issue but having to constantly wait for your feedback could delay getting issues fixed by multiple days

**Comment by SilverAndro** [comment]
Fixed in newest
