### ISSUE TITLE
I have found a Crash when you are crafting an item and you put the recipe in. Its on a 1.16.5 Server.

### ISSUE THREAD

**Issue by MegaLP** [P03W/Veneficium#3]
[23:18:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_2960 net.minecraft.class_3414.method_14833()'
        at net.vene.common.block.entity.SCCSBlockEntity.method_16896(SCCSBlockEntity.java:133) ~[Veneficium-1.2.1.jar:?]
        at net.minecraft.class_1937.method_18471(class_1937.java:510) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:429) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
        ... 5 more

**Comment by SilverAndro** [comment]
Again, bug report titles should be concise, you should provide if your running on a dedicated server, and any additional mods

This is again a simple issue, but I really need to know more if something more complicated comes up

**Comment by SilverAndro** [comment]
Fixed in latest
